$script = <<SCRIPT
	#!/bin/bash

	# Server name, User and Password
	HOSTNAME="Dev"
	USERR="david"
	PASSWORDD="david"

	#Create $USERR user
	sudo useradd -m $USERR
	sudo echo $USERR:$PASSWORDD | sudo /usr/sbin/chpasswd
	sudo usermod -s /bin/bash $USERR
	sudo adduser $USERR sudo

	#new repos
	echo "[vagrant provisioning] Adding repositories..."
	sudo apt-get install software-properties-common -y
	sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
	sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
	sudo add-apt-repository -y ppa:webupd8team/sublime-text-3
	curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
	sudo apt-get update

	#System
	echo "[vagrant provisioning] Installing VirtualBox..."
	sudo apt-get install -y lubuntu-desktop virtualbox-guest-dkms virtualbox-guest-utils virtualbox-guest-x11 xinit

	#Chrome
	echo "[vagrant provisioning] Installing Chrome..."
	sudo apt-get install -y google-chrome-stable

	#Nodejs + Golang + Sublimetext
	echo "[vagrant provisioning] Installing Node.js, Golang, Sublimetext3..."
	sudo apt-get install -y nodejs golang sublime-text

	#Docker and compose
	echo "[vagrant provisioning] Installing Docker..."
	sudo wget -qO- https://get.docker.com/ | sh
	sudo systemctl start docker
	sudo systemctl enable docker
	sudo curl -L https://github.com/docker/compose/releases/download/1.2.0/docker-compose-`uname -s`-`uname -m` > docker-compose && chmod +x docker-compose && sudo mv docker-compose /usr/local/bin/
	sudo curl -L https://raw.githubusercontent.com/docker/compose/1.2.0/contrib/completion/bash/docker-compose > docker-compose && sudo mv docker-compose /etc/bash_completion.d

	#Add $USERR user to docker group, vboxsf	
	sudo gpasswd -a $USERR docker
	sudo service docker restart
	sudo adduser $USERR vboxsf	
	
	#Timezone, Language
	echo "[vagrant provisioning] Configuring Timezone & Language..."
	sudo timedatectl set-timezone Europe/Madrid
	sudo apt-get install -y language-pack-ca language-pack-gnome-ca language-pack-ca-base language-pack-gnome-ca-base xinit
	sudo update-locale LANG=ca_ES.UTF-8 LC_MESSAGES=POSIX
	echo "/usr/bin/ibus-daemon -d" >> ~/.bashrc

	#Timezone, Language
	echo "[vagrant provisioning] Wallpaper..."
	sudo wget  https://farm6.staticflickr.com/5282/5290604395_ed62791a28_o_d.jpg -O /usr/share/lubuntu/wallpapers/1510-lubuntu-default-wallpaper.png

	#Remove light-locker
	sudo apt-get -y remove light-locker

	#Hostname
	echo "[vagrant provisioning] Setting hostname..."
	sudo hostname $HOSTNAME

	#Start
	sudo startx	
SCRIPT


Vagrant.configure(2) do |config|
  
  config.vm.box = "ubuntu/wily64"

  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "1024"
    vb.name = "Dev"
  end

  config.vm.provision "shell", inline: $script

end
