$script = <<SCRIPT
	#!/bin/bash

	#new repos
	#sudo add-apt-repository -y ppa:webupd8team/java
	sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
	sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
	sudo apt-get update

	#System
	sudo apt-get install -y lubuntu-desktop virtualbox-guest-dkms virtualbox-guest-utils virtualbox-guest-x11 xinit

	#Chrome
	sudo apt-get install -y google-chrome-stable

	#Docker and compose
	sudo wget -qO- https://get.docker.com/ | sh
	#sudo apt-get install -y docker.io
	sudo systemctl start docker
	sudo systemctl enable docker
	sudo curl -L https://github.com/docker/compose/releases/download/1.2.0/docker-compose-`uname -s`-`uname -m` > docker-compose && chmod +x docker-compose && sudo mv docker-compose /usr/local/bin/
	sudo curl -L https://raw.githubusercontent.com/docker/compose/1.2.0/contrib/completion/bash/docker-compose > docker-compose && sudo mv docker-compose /etc/bash_completion.d/

	#Timezone, Language
	sudo timedatectl set-timezone Europe/Madrid
	sudo apt-get install -y language-pack-ca language-pack-gnome-ca language-pack-ca-base language-pack-gnome-ca-base xinit
	sudo update-locale LANG=ca_ES.UTF-8 LC_MESSAGES=POSIX

	#Gencat customization
	sudo mkdir /home/vagrant/Desktop
	sudo mkdir /home/vagrant/Pictures
	sudo cp /usr/share/lubuntu/wallpapers/1504-lubuntu-default-wallpaper.png /usr/share/lubuntu/wallpapers/1504-lubuntu-default-wallpaper_bck.png
	sudo wget http://canigo.ctti.gencat.cat/devenv/fonspantalla_1280.png -O /usr/share/lubuntu/wallpapers/1504-lubuntu-default-wallpaper.png
	sudo wget http://canigo.ctti.gencat.cat/img/favicon.ico -O /home/vagrant/Pictures/favicon.ico
	sudo wget http://canigo.ctti.gencat.cat/devenv/documentacio-framework.desktop -O /home/vagrant/Desktop/documentacio-framework.desktop
	sudo wget http://canigo.ctti.gencat.cat/devenv/web-canigo.desktop -O /home/vagrant/Desktop/web-canigo.desktop
	sudo wget http://canigo.ctti.gencat.cat/devenv/jira.desktop -O /home/vagrant/Desktop/jira.desktop
	sudo wget http://canigo.ctti.gencat.cat/devenv/svn.desktop -O /home/vagrant/Desktop/svn.desktop
	sudo wget http://canigo.ctti.gencat.cat/devenv/eclipse.desktop -O /home/vagrant/Desktop/eclipse.desktop

	#DEVELOPMENT ENVIRONMENT
	#sudo apt-get -y install oracle-java7-installer
	sudo apt-get -y install openjdk-7-jdk

	sudo wget http://www.mirrorservice.org/sites/download.eclipse.org/eclipseMirror/technology/epp/downloads/release/luna/SR2/eclipse-jee-luna-SR2-linux-gtk-x86_64.tar.gz 
	sudo tar -zxvf eclipse*.tar.gz 
	sudo rm eclipse*.tar.gz 
	sudo mv eclipse* /opt/

	#Maven
	#sudo apt-get install maven2
	
	#Maven plugin eclipse
	#/opt/eclipse/eclipse -nosplash -application org.eclipse.equinox.p2.director -repository https://repository.sonatype.org/content/repositories/forge-sites/m2e/0.10.0/S/20100205-2200/ -installIU org.maven.ide.eclipse.feature.feature.group

	#Canigo 3.1.1 Plug-ins Feature 1.2.1
	#/opt/eclipse/eclipse -nosplash -application org.eclipse.equinox.p2.director -repository  http://repos.canigo.ctti.gencat.cat/repository/maven2/cat/gencat/ctti/canigo.plugin/update-site/ -installIU cat.gencat.ctti.canigo.feature.feature.group

	#Start
	sudo startx	
SCRIPT

Vagrant.configure(2) do |config|
  
  config.vm.box = "ubuntu/vivid64"

  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "1280"
    vb.name = "CanigoDev"
  end

  config.vm.provision "shell", inline: $script

end
